# Generated by Django 4.2.4 on 2023-08-25 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 14, 3, 52, 548437, tzinfo=datetime.timezone.utc)),
        ),
    ]
