# Generated by Django 4.2.4 on 2023-08-25 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 16, 37, 15, 478576, tzinfo=datetime.timezone.utc)),
        ),
    ]
