# Generated by Django 4.2.4 on 2023-09-01 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jira', '0008_status_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(default=models.DateTimeField())),
                ('created_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('notes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.notes')),
                ('responsible_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tasks', to=settings.AUTH_USER_MODEL)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jira.status')),
            ],
        ),
    ]
