# Generated by Django 4.2.4 on 2023-09-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='project_id',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='jira.project'),
            preserve_default=False,
        ),
    ]
