# Generated by Django 4.2.4 on 2023-09-02 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jira', '0013_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recevie_comments_get_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
