# Generated by Django 4.2.4 on 2023-09-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0014_alter_comments_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
